### ISSUE TITLE
1.20.1 for fabric apparently is only for 1.20.2

### ISSUE THREAD

**Issue by Dashy22** [bigenergy/achievement-optimizer#11]
It's the wrong version or you just uploaded the wrong version by accident.

**Comment by bigenergy** [comment]
where? curseforge?

**Comment by Dashy22** [comment]
on modrinth

**Comment by bigenergy** [comment]
More info? Logs, errors?

**Comment by maxutka99** [comment]
Mods:
  [✔] AchievementOptimizer-fabric-1.20.1-1.0.0
  [✔] fabric-api-0.92.1+1.20.1

Params:
  --username  --version 1.20.1 --gameDir /home/gnt/.local/share/PrismLauncher/instances/achievment optimizer test/.minecraft --assetsDir /home/gnt/.local/share/PrismLauncher/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx6144m, -Duser.language=en]


Minecraft process ID: 77599


[22:50:44] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[22:50:44] [main/WARN]: Mod resolution failed
[22:50:44] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED achiopt 1.0 {depends minecraft @ [1.20.2]}, ROOT_FORCELOAD_SINGLE achiopt 1.0]
[22:50:44] [main/INFO]: Reason: [HARD_DEP achiopt 1.0 {depends minecraft @ [1.20.2]}]
[22:50:44] [main/INFO]: Fix: add [], remove [], replace [[achiopt 1.0] -> add:achiopt 1 ([(-∞,∞)])]
[22:50:44] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'AchievementOptimizer' (achiopt) 1.0 with any version that is compatible with:
		 - minecraft 1.20.1
More details:
	 - Mod 'AchievementOptimizer' (achiopt) 1.0 requires version 1.20.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?]

**Comment by ImBehinYa** [comment]
can confirm

**Comment by bigenergy** [comment]
fixed in 1.0.1, thx
